name: Continuous Integration
on: [pull_request, push]
jobs:
  test: # <--- INI NAMA WORKFLOW KAMU
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run Lint
        run: npm run lint
      - name: Run Test
        run: npm test